version: '3'

networks:
  saltnet:

services:
  minion:
    image: saltsni
    build: .
    hostname: minion.saltnet.tls
    environment:
      SALT_TRANSPORT: tcp
      SALT_TRANSPORT_TLS: enabled
      SALT_MASTER_ID: master.saltnet.tls
    networks:
      saltnet:
        aliases:
          - minion.saltnet.tls
  
  master:
    image: saltsni
    build: .
    hostname: master.saltnet.tls
    environment:
      SALT_MASTER: enabled
      SALT_TRANSPORT: tcp
      SALT_TRANSPORT_TLS: enabled
      SALT_MASTER_ID: master.saltnet.tls
    networks:
      saltnet:
        aliases:
          - master.saltnet.tls
